name: Deploy to remote

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOST: root@5.42.100.122
      DEPLOY_DIRECTORY: /root/apps/url-shortener
      CONFIG_PATH: /root/apps/url-shortener/config/prod.yaml
      ENV_FILE_PATH: /root/apps/url-shortener/.env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy with rsync
        run: ssh-keyscan -p ${{ secrets.REMOTE_SSH_PORT }} -H 5.42.100.122 >> ~/.ssh/known_hosts
      - name: Deploy to remote server
        run: |
          sudo apt-get install -y ssh rsync
          echo "$DEPLOY_SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem -p ${{ secrets.REMOTE_SSH_PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "mkdir -p ${{ env.DEPLOY_DIRECTORY }}"
          rsync -avz -e 'ssh -i deploy_key.pem -p ${{ secrets.REMOTE_SSH_PORT }} -o StrictHostKeyChecking=no' --exclude='.git' ./ ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: Create environment file on server
        run: |
          ssh -i deploy_key.pem -p ${{ secrets.REMOTE_SSH_PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "\
          touch ${{ env.ENV_FILE_PATH }} && \
          chmod 600 ${{ env.ENV_FILE_PATH }} && \
          echo 'POSTGRES_PASS=${{ secrets.POSTGRES_PASS }}' > ${{ env.ENV_FILE_PATH }}"
      - name: Start application
        run: |
          ssh -i deploy_key.pem -p ${{ secrets.REMOTE_SSH_PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "cd ${{ env.DEPLOY_DIRECTORY }} && docker-compose up -d"